openapi: 3.0.0
info:
  title: My API Training Project 
  version: 1.0.0
tags: 
  - name: person_end_point
    description: This is a person related operation
paths:
  /person/{personId}:
    get:
      tags: 
       - person_end_point
      parameters: 
        - in: path
          name: personId
          required: true
          schema:
            type: integer
            example: 1234
      responses:
        200:
          description: select person 
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    nId:
                      type: integer
                      example: 4
                    age:
                      type: integer
                      example: 28
                    firstName:
                      type: string
                      example: John 
                    lastName:
                      type: string
                      example: Doe
                    dateBirth:
                      type: string
                      example: "1972-06-30"
                  required: 
                      - nId
        500:
          $ref: '#/components/responses/500ApiError'
  /person/add:
    post:
      tags: 
       - person_end_point
      description: Adding a person  to the list
      requestBody:
        content:
          application/json:
            schema:
               $ref: '#/components/schemas/person'
      responses:
        200:
          description: The person has been saved 
          
        500:
          $ref: '#/components/responses/500ApiError'
          
  /person:
    get:
      tags: 
       - person_end_point
      parameters:
        - $ref: '#/components/parameters/PageNumber'
        - $ref: '#/components/parameters/PageSize'
      responses:
        200:
          description: This is a list of pepole  
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/person'
                  
        500:
          $ref: '#/components/responses/500ApiError'
components:
  parameters:
    PageNumber:
      in: query
      name: pageNumber
      description: Page number to return
      required: false
      schema:
        type: integer
        example: 1
    PageSize:
      in: query
      name: pageSize
      description: Number of result in the page
      required: false
      schema:
        type: integer
        example: 10
        maximum: 100
  schemas:
    person:
      type: object
      required: 
        - nId
      properties:
        nId:
          type: integer
          example: 4
        age:
          type: integer
          example: 28
        firstName:
          type: string
          example: John 
        lastName:
          type: string
          example: Doe
        dateBirth:
          type: string
          example: "1972-06-30"
  responses:
    500ApiError:
      description: This is an unexpected error
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: string
                example: 500
              message:
                type: string
                example : you have an error in he server side 
      
      
      
      
      
    
          